# Generated by Django 5.1.1 on 2024-09-17 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.SmallIntegerField()),
                ('gear', models.CharField(choices=[('m', 'Manuel'), ('a', 'Automatic')], max_length=10)),
                ('image', models.TextField()),
                ('rent_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('availability', models.BooleanField(default=True)),
                ('motor', models.CharField(max_length=20)),
                ('km', models.IntegerField()),
                ('gps', models.BooleanField(default=False)),
                ('anti_lock_brakes', models.BooleanField(default=False)),
                ('remote_keyless', models.BooleanField(default=False)),
                ('rear_set_screen', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_car', to='rent_a_car.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
