# Generated by Django 5.1.1 on 2024-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
